# Generated by Django 5.2.4 on 2025-09-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avatar',
            field=models.FilePathField(blank=True, match='.*\\.(jpg|jpeg|png|gif|svg)$', max_length=255, null=True, path='/home/denis/Desktop/new_Projects/freelance/Totalizator_simulator/Django/media/team_avatars', verbose_name='Аватар'),
        ),
    ]
