# Generated by Django 5.2.4 on 2025-10-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fanpoints',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Накопленные FanPoints команды за текущий цикл', max_digits=12),
        ),
    ]
