# Generated by Django 5.2.4 on 2025-07-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance_cached',
            field=models.DecimalField(decimal_places=6, default=50000, max_digits=12, verbose_name='Кэш баланса'),
        ),
    ]
