# Generated by Django 5.2.4 on 2025-08-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_balance_cached'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('end_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('background_color', models.CharField(help_text='HEX цвет для фона (например, #353353)', max_length=7)),
                ('border_color', models.CharField(help_text='HEX цвет для рамки (например, #454242)', max_length=7)),
            ],
        ),
    ]
