# Generated by Django 5.2.4 on 2025-10-02 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_betcoupon_payout_scheme'),
        ('users', '0002_fanpool_customuser_favorite_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorinterval',
            name='payout_scheme',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='color_scheme', to='games.payoutscheme', verbose_name='Схема выплат'),
            preserve_default=False,
        ),
    ]
