# Generated by Django 5.2.4 on 2025-08-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_colorinterval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorinterval',
            name='end_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Конец интервала'),
        ),
        migrations.AlterField(
            model_name='colorinterval',
            name='start_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Начало интервала'),
        ),
    ]
