# Generated by Django 5.2.4 on 2025-10-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_betcoupon_payout_scheme'),
        ('users', '0004_alter_colorinterval_payout_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorinterval',
            name='payout_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_intervals', to='games.payoutscheme', verbose_name='Схема выплат'),
        ),
    ]
