# Generated by Django 5.2.4 on 2025-10-11 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_colorinterval_payout_scheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FanPool',
        ),
    ]
