version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db_totalizator
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "6020:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: