# Generated by Django 5.2.4 on 2025-09-02 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_variants', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BetVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_count', models.PositiveSmallIntegerField(default=0)),
                ('win_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('win_multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_win', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BiggestWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jackpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Джекпот',
                'verbose_name_plural': 'Джекпот',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('1', 'Победа 1'), ('X', 'Ничья'), ('2', 'Победа 2')], help_text="Итоговый результат: '1', 'X' или '2'", max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_count', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('selection_end_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Ожидание начала'), ('selection', 'Выбор ставок'), ('calculation', 'Расчёт результатов'), ('payout', 'Выплата'), ('finished', 'Завершён')], default='selection', max_length=20)),
                ('game_hash', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoundStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_pool', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_pool', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jackpot_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jackpot_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_win', models.DecimalField(decimal_places=2, max_digits=12)),
                ('count_winners_by_category', models.JSONField(default=dict)),
                ('payout_by_category', models.JSONField(default=dict)),
                ('best_multiplier', models.JSONField(default=dict)),
                ('biggest_win', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('win1', 'Победа 1'), ('draw', 'Ничья'), ('win2', 'Победа 2')], max_length=5)),
            ],
        ),
    ]
