# Generated by Django 5.2.4 on 2025-09-02 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='betcoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='betvariant',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='games.betcoupon'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='payoutcategory',
            index=models.Index(condition=models.Q(('active', True)), fields=['matched_count'], name='payout_active_matched_idx'),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['status', '-id'], name='round_status_id_desc'),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='games.round'),
        ),
        migrations.AddField(
            model_name='betcoupon',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='games.round'),
        ),
        migrations.AddField(
            model_name='roundstats',
            name='round',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='games.round'),
        ),
        migrations.AddField(
            model_name='selectedoutcome',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.match'),
        ),
        migrations.AddField(
            model_name='selectedoutcome',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='games.betvariant'),
        ),
        migrations.AddIndex(
            model_name='betvariant',
            index=models.Index(fields=['coupon', 'matched_count'], name='variant_coupon_matched_idx'),
        ),
        migrations.AddIndex(
            model_name='betvariant',
            index=models.Index(fields=['coupon', 'id'], name='variant_coupon_id_idx'),
        ),
        migrations.AddIndex(
            model_name='betcoupon',
            index=models.Index(fields=['user', 'id'], name='coupon_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='betcoupon',
            index=models.Index(fields=['round', 'user', 'id'], name='coupon_round_user_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='selectedoutcome',
            constraint=models.UniqueConstraint(fields=('variant', 'match'), name='uniq_variant_match'),
        ),
    ]
