# Generated by Django 5.2.4 on 2025-07-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('selection', 'Выбор ставок'), ('calculation', 'Расчёт результатов'), ('payout', 'Выплата'), ('finished', 'Завершён')], default='selection', max_length=20)),
                ('total_pool', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jackpot_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('game_hash', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
