# Generated by Django 5.2.4 on 2025-07-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='number',
        ),
    ]
