# Generated by Django 5.2.4 on 2025-09-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='total_pool',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Текущий пул ставок (живой, обновляется при создании купонов)', max_digits=12),
        ),
    ]
