# Generated by Django 5.2.4 on 2025-07-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_round_number'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_win1', models.DecimalField(decimal_places=2, default=33.0, max_digits=5)),
                ('prob_draw', models.DecimalField(decimal_places=2, default=33.0, max_digits=5)),
                ('prob_win2', models.DecimalField(decimal_places=2, default=33.0, max_digits=5)),
                ('result', models.CharField(blank=True, choices=[('1', 'Победа 1'), ('X', 'Ничья'), ('2', 'Победа 2')], help_text="Итоговый результат: '1', 'X' или '2'", max_length=1, null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='games.round')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.team')),
            ],
        ),
    ]
