# Generated by Django 5.2.4 on 2025-09-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_round_total_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='total_pool',
            new_name='live_pool',
        ),
    ]
