# Generated by Django 5.2.4 on 2025-09-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_total_pool_round_live_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='betcoupon',
            name='is_seen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='betcoupon',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='betcoupon',
            name='win_amount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
