# Generated by Django 5.2.4 on 2025-09-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_betcoupon_is_seen_betcoupon_is_winner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jackpot',
        ),
        migrations.RemoveField(
            model_name='payoutcategory',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='round',
            name='live_pool',
        ),
        migrations.RemoveField(
            model_name='roundstats',
            name='jackpot_after',
        ),
        migrations.RemoveField(
            model_name='roundstats',
            name='jackpot_before',
        ),
        migrations.RemoveField(
            model_name='roundstats',
            name='payout_pool',
        ),
        migrations.RemoveField(
            model_name='roundstats',
            name='total_pool',
        ),
        migrations.AddField(
            model_name='payoutcategory',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
