# Generated by Django 5.2.4 on 2025-07-23 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_betcoupon_betvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betvariant',
            name='selected_outcomes',
        ),
        migrations.CreateModel(
            name='SelectedOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('win1', 'Победа 1'), ('draw', 'Ничья'), ('win2', 'Победа 2')], max_length=5)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.match')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='games.betvariant')),
            ],
        ),
    ]
