# Generated by Django 5.2.4 on 2025-09-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_delete_jackpot_remove_payoutcategory_percent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayoutCategory',
        ),
    ]
