# Generated by Django 5.2.4 on 2025-07-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_betvariant_selected_outcomes_selectedoutcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='prob_draw',
        ),
        migrations.RemoveField(
            model_name='match',
            name='prob_win1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='prob_win2',
        ),
    ]
