# Generated by Django 5.2.4 on 2025-07-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_match_prob_draw_remove_match_prob_win1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jackpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Джекпот',
                'verbose_name_plural': 'Джекпот',
            },
        ),
        migrations.RemoveField(
            model_name='round',
            name='jackpot_snapshot',
        ),
        migrations.AlterField(
            model_name='round',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание начала'), ('selection', 'Выбор ставок'), ('calculation', 'Расчёт результатов'), ('payout', 'Выплата'), ('finished', 'Завершён')], default='selection', max_length=20),
        ),
    ]
