# Generated by Django 5.2.4 on 2025-09-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_delete_payoutcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('coefficients', models.JSONField(default=dict, help_text='Словарь с коэффициентами для 1–10 угаданных матчей')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
