# Generated by Django 5.2.4 on 2025-07-26 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_jackpot_remove_round_jackpot_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_pool', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_pool', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jackpot_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jackpot_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('winners_by_category', models.JSONField(default=dict)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='games.round')),
            ],
        ),
    ]
