# Generated by Django 5.2.4 on 2025-10-01 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_payoutscheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='betcoupon',
            name='payout_scheme',
            field=models.ForeignKey(default='1', help_text='Схема выплат, по которой рассчитывается купон', on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='games.payoutscheme'),
            preserve_default=False,
        ),
    ]
