# Generated by Django 5.2.4 on 2025-10-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_betcoupon_payout_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, default=1.0, help_text='Процент от всех ставок в раунде, идущий в фонд', max_digits=5)),
                ('rounds_interval', models.PositiveIntegerField(default=10, help_text='Каждые N раундов разыгрывать фонд')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Текущая сумма фонда', max_digits=12)),
                ('rounds_since_distribution', models.PositiveIntegerField(default=0, verbose_name='Раундов прошло с розыгрыша')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
