# Generated by Django 5.2.4 on 2025-10-19 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_fanpool'),
        ('teams', '0003_team_fanpoints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanpool',
            name='rounds_interval',
            field=models.PositiveIntegerField(default=1000, help_text='Каждые N раундов разыгрывать фонд'),
        ),
        migrations.CreateModel(
            name='Playoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('end_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='games.round')),
                ('start_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='games.round')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayoffMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_slots', models.PositiveIntegerField(help_text='Номинальная стадия: 16, 8, 4, 2')),
                ('pair_index', models.PositiveIntegerField(help_text='Порядковый номер пары в стадии, начиная с 1')),
                ('seed1', models.PositiveIntegerField(help_text='Посев team1 в момент старта стадии')),
                ('seed2', models.PositiveIntegerField(blank=True, help_text='Посев team2 в момент старта стадии', null=True)),
                ('is_bye', models.BooleanField(default=False, help_text='Автопроход (нет соперника)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VOTING', 'Voting'), ('FINISHED', 'Finished')], default='PENDING', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('playoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='games.playoff')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playoff_team1', to='teams.team')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playoff_team2', to='teams.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playoff_winner', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='FanVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('attack', 'Атака'), ('defense', 'Защита'), ('speed', 'Скорость'), ('tactic', 'Тактика')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.playoffmatch')),
            ],
            options={
                'verbose_name': 'Голос фаната',
                'verbose_name_plural': 'Голоса фанатов',
                'unique_together': {('user', 'match')},
            },
        ),
    ]
