# Generated by Django 5.2.4 on 2025-08-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_biggestwin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payoutcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='payoutcategory',
            name='order',
        ),
    ]
