# Generated by Django 5.2.4 on 2025-10-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_fanpool_rounds_interval_playoff_playoffmatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanpool',
            name='rounds_since_distribution',
        ),
        migrations.RemoveField(
            model_name='fanpool',
            name='updated_at',
        ),
    ]
