# Generated by Django 5.2.4 on 2025-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_payoutcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundstats',
            name='biggest_win_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='round',
            name='game_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
