# Generated by Django 5.2.4 on 2025-08-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_roundstats_biggest_win_x_alter_round_game_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='betvariant',
            name='win_multiplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
