# Generated by Django 5.2.4 on 2025-10-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_remove_fanpool_rounds_since_distribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='server_seed',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='server_seed_hash',
            field=models.CharField(default='1', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fanpool',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Текущая сумма фонда', max_digits=12),
        ),
    ]
