# Generated by Django 5.2.4 on 2025-10-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_match_server_seed_match_server_seed_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='game_hash',
            new_name='server_seed',
        ),
        migrations.RemoveField(
            model_name='match',
            name='server_seed',
        ),
        migrations.RemoveField(
            model_name='match',
            name='server_seed_hash',
        ),
        migrations.AddField(
            model_name='round',
            name='server_seed_hash',
            field=models.CharField(default='1', max_length=64),
            preserve_default=False,
        ),
    ]
