# Generated by Django 5.2.4 on 2025-10-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_rename_game_hash_round_server_seed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanpool',
            name='checkpoint_amount',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Зафиксированная сумма фонда', max_digits=12),
        ),
    ]
